name: Deploy Website
on:
  push:
    branches:
      - docker-test

jobs:
  build:
    container: sergiud/texlive
    name: Fetch & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Build
        run: |
          make website
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: website-directory
          path: website/
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dowload Artifact
        uses: actions/download-artifact@v1
        with:
          name: website-directory
          path: website/
      
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: website
          keep_history: false
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
